=encoding UTF-8

=head1 NAME

OpenTelemetry::Propagator::None - A context propagator for OpenTelemetry that does nothing

=head1 SYNOPSIS

    use OpenTelemetry::Propagator::None;

    my $propagator = OpenTelemetry::Propagator::None->new;

    # Does nothing :(
    my $carrier = {};
    $propagator->inject( $carrier, $context );

    # Still nothing :(
    my $new_context = $propagator->extract( $carrier, $context );

=head1 DESCRIPTION

This package defines a no-op propagator class that implements the
L<OpenTelemetry::Propagator> interface.

=head1 METHODS

=head2 new

    $propagator = OpenTelemetry::Propagator::None->new

Constructs a new instance of this propagator. This propagator will do nothing.

=head1 SEE ALSO

=over

=item L<OpenTelemetry::Context>

=item L<OpenTelemetry::Propagator>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2023 by José Joaquín Atria.

This is free software; you can redistribute it and/or modify it under the same
terms as the Perl 5 programming language system itself.
