=encoding utf8

=head1 NAME

OpenTelemetry::Integration - Support for legacy OpenTelemetry instrumentations

=head1 DESCRIPTION

The namespace for OpenTelemetry instrumentation libraries has been renamed
to L<OpenTelemetry::Instrumentation>. Please refer to that document instead.

This module is kept here so that existing code that uses the old name
continues to work, but new code should not use this module.

=head1 COPYRIGHT

This software is copyright (c) 2024 by José Joaquín Atria.

This is free software; you can redistribute it and/or modify it under the same
terms as the Perl 5 programming language system itself.
